const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../dist');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const nodes=new Map();
const el=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',classList:{add(){},remove(){},toggle(){}},scrollIntoView(){},showModal(){},close(){},click(){},focus(){},setSelectionRange(){}});return nodes.get(selector)};
const saved={},registered=[];
const context=vm.createContext({console,URL,Date,Error,JSON,FormData,Image:class{},document:{querySelector:el,querySelectorAll:()=>[],modelContext:{registerTool:t=>registered.push(t)}},window:{addEventListener(){},scrollTo(){}},location:{hash:'#landing'},localStorage:{getItem:k=>saved[k],setItem:(k,v)=>saved[k]=v},setTimeout:()=>1,clearTimeout(){}});
vm.runInContext(source,context);
const run=s=>vm.runInContext(s,context);
for(const route of ['landing','home','assistant','documents','images','solutions','history']){
 context.location.hash='#'+route;run('route()');
 assert.ok(el('#app').innerHTML.length>500,route+' renders');
 assert.ok(el('#app').innerHTML.includes('CloudCore'),route+' branding');
}
assert.ok(el('#app').innerHTML.includes('CONVERSATION LIBRARY'));
const initial=run('chats.length');
run("assistantMode='Proposal Writer';sendMessage('Prepare a document proposal for a cloud migration')");
assert.equal(run('messages.length'),2);
assert.equal(JSON.parse(saved['cloudcore-chats']).length,initial+1);
assert.ok(run("messages[1].content.includes('Recommended structure') && messages[1].sources.includes('Proposal framework')"));
const id=run('currentChat');
run("actions('new-chat',{})");
assert.equal(run('messages.length'),0);
assert.equal(JSON.parse(saved['cloudcore-chats']).length,initial+1);
run(`actions('open-chat',{dataset:{id:${JSON.stringify(id)}}})`);
assert.equal(run('messages.length'),2);
run("actions('assistant-mode',{dataset:{mode:'Service Support'}})");
assert.equal(run('assistantMode'),'Service Support');
run("actions('doc-tab',{dataset:{tab:'Risks & Obligations'}})");
assert.equal(run('docTab'),'Risks & Obligations');
run("selectDocument({name:'invalid.exe',size:1})");
assert.equal(run('docFile'),null);
run("selectDocument({name:'too-big.pdf',size:60*1048576})");
assert.equal(run('docFile'),null);
run("selectDocument({name:'proposal.pdf',size:1024})");
assert.equal(run('docFile.name'),'proposal.pdf');
run("selectImage({type:'text/plain',size:1})");
assert.equal(run('imageFile'),null);
run("selectImage({type:'image/png',size:21*1048576})");
assert.equal(run('imageFile'),null);
run("actions('example-image',{dataset:{example:'diagram'}})");
assert.equal(run('activeImageExample'),'diagram');
run("actions('solution-filter',{dataset:{filter:'Cloud'}})");
assert.equal(run('solutionFilter'),'Cloud');
run("actions('toggle-compare',{dataset:{id:'cloud'}})");
run("actions('toggle-compare',{dataset:{id:'security'}})");
assert.equal(run('solutionCompare.length'),2);
run("actions('history-filter',{dataset:{filter:'Guided'}})");
assert.equal(run('historyFilter'),'Guided');
assert.equal(registered.length,1);
registered[0].execute({screen:'solutions'});
assert.equal(context.location.hash,'solutions');
assert.throws(()=>registered[0].execute({screen:'invalid'}));
assert.equal(run("esc('<script>')"),'&lt;script&gt;');
for(const asset of ['index.html','style.css','app.js','assets/hero.png','assets/favicon.svg','assets/cloudcore-mark.png','assets/reference-home.png','assets/diagram.svg'])assert.ok(fs.existsSync(path.join(root,asset)),asset);
assert.equal(source.includes(String.fromCharCode(0xfffd)),false,'no text encoding replacement characters');
console.log('Passed: seven routes, distinct workspaces, chat persistence, assistant modes, document analysis tabs, upload validation, image scenarios, solution filters and comparison, history filters, WebMCP navigation, HTML escaping, and local assets.');
